<?php
/*
 * Generated by CRUDigniter v3.0 Beta
 * www.crudigniter.com
 */

class Seguridad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('cct_model');

    }

    /*
     * Get seguridad by username
     */
    function get_all_seguridad_xcct($cct)
    {
      $string = "SELECT username FROM  seguridad WHERE username LIKE '%".$cct."%'";
      $query = $this->db->query($string);

      return $query->result_array();
    }
    /*
     * Get seguridad by idusuario
     */
    function get_seguridad($idusuario)
    {
        return $this->db->get_where('seguridad',array('idusuario'=>$idusuario))->row_array();
    }

    /*
     * Get all seguridad
     */
    function get_all_seguridad()
    {
        return $this->db->get('seguridad')->result_array();
    }

    /*
     * function to add new seguridad
     */
    function add_seguridad($params)
    {
        $this->db->insert('seguridad',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update seguridad
     */
    function update_seguridad($idusuario,$params)
    {
        $this->db->where('idusuario',$idusuario);
        return $this->db->update('seguridad',$params);
        /*
        if($response)
        {
            return "seguridad updated successfully";
        }
        else
        {
            return "Error occuring while updating seguridad";
        }
        */
    }

    /*
     * function to delete seguridad
     */
    function delete_seguridad($idusuario)
    {
        $response = $this->db->delete('seguridad',array('idusuario'=>$idusuario));
        if($response)
        {
            return "seguridad deleted successfully";
        }
        else
        {
            return "Error occuring while deleting seguridad";
        }
    }

    /**
     * Comprueba si un usuario existe en la base de datos para edicion de formulario.
     *
     * @param string $username Nombre de usuario ingresado en el formulario.
     * @return boolean TRUE si existe en la base de datos
    */
    function existe_username($username,$id_usuario)
    {
        $resultado = $this->db->get_where('seguridad', array('username' => $username,'idusuario !='=>$id_usuario));
        return $resultado->num_rows() > 0 ? TRUE : FALSE;
    }

    /**
     * Para el nuevo registro agregado en la tabla Usuario, se ingresa
     * el correspondiente registro en Seguridad con username y clave
     * generados automáticamente.
     *
     * @param  int     $id_nuevo_usuario Último registro insertado en la tabla Usuario
     * @param  string  $uname Nombre de usuario ingresado en el formulario
     * @param  string  $contrasena       Conraseña generada automáticamente
     * @param  int     $perfil Escolar o central
     * @param  int     $id_cct Clave de CCT del usuario que dará de alta
     * @return array   username, clave e idusuario generado automáticamente
    */
    function genera_usuario($id_nuevo_usuario, $uname, $contrasena, $perfil = 2, $id_cct)
    {
        if($perfil === '1')
        {
            $username = $uname.'@central';
        }
        else
        {
            $reg_cct = $this->cct_model->get_cct($id_cct);
            $username = $uname.'@'.$reg_cct['cct'].'.M';
        }

        $params = array('username' => $username, 'clave' => md5($contrasena), 'idusuario' => $id_nuevo_usuario);
        // $params = array('username' => $username, 'clave' => ($contrasena), 'idusuario' => $id_nuevo_usuario);// 20180727 MH
        $this->add_seguridad($params);
        return array('username' => $username, 'idusuario' => $id_nuevo_usuario, 'clave' => $contrasena);
    }

    function genera_usuario_central($id_nuevo_usuario, $uname, $contrasena)
    {
        $username = $uname.'@central';
        $params = array('username' => $username, 'clave' => md5($contrasena), 'idusuario' => $id_nuevo_usuario,);
        // $params = array('username' => $username, 'clave' => ($contrasena), 'idusuario' => $id_nuevo_usuario,);// 20180727 MH
        $this->add_seguridad($params);
        return array('username' => $username, 'idusuario' => $id_nuevo_usuario, 'clave' => $contrasena);
    }

    function genera_usuario_escolar($id_nuevo_usuario, $uname, $contrasena, $username_creador)
    {
        $variabltemp=preg_split('/@/', $username_creador);
        $cct = ($variabltemp[1]);
        $username = $uname.'@'.$cct;

        $params = array('username' => $username, 'clave' => $contrasena, 'idusuario' => $id_nuevo_usuario);
        // $params = array('username' => $username, 'clave' => ($contrasena), 'idusuario' => $id_nuevo_usuario);// 20180727 MH
        $this->add_seguridad($params);
        return array('username' => $username, 'idusuario' => $id_nuevo_usuario, 'clave' => $contrasena);
    }

    function cambia_clave_usuario($id_usuario, $clave)
    {
        $this->db->where('idusuario', $id_usuario);
        $response = $this->db->update('seguridad', array('clave' => ($clave))); // 20180405 MH
        // $response = $this->db->update('seguridad', array('clave' => md5($clave)));// 20180727 MH -> 20180405 MH
        if($response)
        {
            return TRUE;
        }
        else
        {
            return FALSE;
        }
    }
}
